### ISSUE TITLE
Ejercicio 13 del capitulo 3

### ISSUE THREAD

**Issue by RoblesJP** [LuisJoseSanchez/aprende-java-con-ejercicios#1]
Hola, este ejercicio es del capitulo 3, donde todavía no se llega a ver bucles o condicionales, como debo resolverlo sin aplicar eso?

**Comment by RoblesJP** [comment]
Hola?

**Comment by LuisJoseSanchez** [comment]
Hola, el capítulo 3 tiene 12 ejercicios, no existe el ejercicio nº 13. Seguramente tienes una versión antigua del libro. Entrando en tu cuenta de Leanpub puedes descargarte la última versión del libro "Aprende Java con Ejercicios". Un saludo.
