### ISSUE TITLE
Faltan ficheros en la solución.

### ISSUE THREAD

**Issue by LolaJimenezCortes** [LuisJoseSanchez/aprende-java-con-ejercicios#10]
Estimado Luis,

En la solución que se aporta, faltan los ficheros Carrito.java ElementoDeCarrito.java Producto.java y Catalogo.java

Si los tienes disponibles, se agradece que los subas. En caso contrario trataré de hacerlos y pasártelos.

Saludos...

**Comment by LuisJoseSanchez** [comment]
Hola. Pongo por aquí que se trata de la carpeta `soluciones/15_Sesiones_y_cookies/15.1_Sesiones/S151Ejercicio04/index.jsp` para que se sepa de qué estamos hablando. Voy a mirarlo.

**Comment by LuisJoseSanchez** [comment]
Solucionado. Ya he añadido las clases que faltaban.
<https://github.com/LuisJoseSanchez/aprende-java-con-ejercicios/tree/master/soluciones/15_Sesiones_y_cookies/15.1_Sesiones/S151Ejercicio04/clases>
