### ISSUE TITLE
error de salida del programa.

### ISSUE THREAD

**Issue by adr1ancruz** [LuisJoseSanchez/aprende-java-con-ejercicios#7]
El programa no me da una salida.No muestra las posición en donde estará ubicada el el dígito.
¿me podría aclarar ese error? 
Entiendo yo que el programa pide que ingresemos un numero y posteriormente un dígito y que ese dígito a la hora de unir los dos números ejemplo 3 y 4  seria 34 el dígito 4 esta en la 1 posición si lo vemos que esta recorriendo de 0 a 1 una cifra.

**Comment by LuisJoseSanchez** [comment]
Hola @adr1ancruz Veo que la incidencia es de hace tiempo, se me había pasado ¿A que programa te refieres? ¿De qué capítulo?

**Comment by javierbarbe** [comment]
Buenas!!
Aprovechando el paron de las clases a causa del coronavirus he tenido tiempo de encontrar tu repositorio y ampliar ejercicios... 
La duda que te consulto es sobre el ejercicio de AmpliandoGestesimal que es el 13 del tema de Colecciones y Diccionarios.. en una parte del codigo haces referencia a posicion... pero no la veo definida en ninguna parte... asi que no sé a qué te refieres con "posicion" 
Pego el segmento de codigo al que me refiero: 
     do {
            codigoIntro = System.console().readLine();
            if (posicion(codigoIntro) != -1) {
              System.out.print("Ese código ya existe.\nIntroduzca otro código: ");
            }
          } while  (posicion(codigoIntro) != -1);

Un saludo 
Gracias de antemano

**Comment by LuisJoseSanchez** [comment]
Hola @javierbarbe 
posicion es una función que da precisamente la posición dentro de la lista del artículo cuyo código se pasa como parámetro, en este caso codigoIntro. Si no se encuentra el código, la función devuelve un -1.
De todas formas, he visto que este programa se ha quedado un poco anticuado. Una mejora sería cambiar posicion() por exists() o indexOf() que ya están implementados. Lo que haría falta para poder usar exits() e indexOf() es definir los métodos equals() y compareTo() en la clase Articulo, para que Java sepa cómo comparar artículos.
Espero que te sirva de algo lo que te cuento 😉
