### ISSUE TITLE
error

### ISSUE THREAD

**Issue by shaul403** [LuisJoseSanchez/aprende-java-con-ejercicios#8]
disculpa me e guiado en tus ejercicios y e sale esto sabes como puedo solucionarlo?
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.io.Console.readLine()" because the return value of "java.lang.System.console()" is null

**Comment by LuisJoseSanchez** [comment]
Hola ¿puedes poner el código que te provoca ese error?

**Comment by shaul403** [comment]
public static void main(String[] args) {
    
    int intentos = 4;
    int numeroIntroducido;
    boolean acertado = false;
    
    do {
      System.out.print("Introduzca la clave de la caja fuerte: ");
      numeroIntroducido = Integer.parseInt(System.console().readLine());
      
      if (numeroIntroducido == 8888) {
        acertado = true;
      } else {
        System.out.println("Clave incorrecta");
      }
      
      intentos--;
  
    } while((intentos > 0) && (!acertado));
    
    if (acertado) {
      System.out.println("Ha abierto la caja fuerte.");
    } else {
      System.out.println("Lo siento, ha agotado las 4 oportunidades.");
    }
  }
}
//perdone la demora//

**Comment by LuisJoseSanchez** [comment]
Hola. Ese código funciona bien compilado y ejecutado desde línea de comandos o desde IDEs que utilizan la consola como por ejemplo Geany. El error que comentas, lo dan IDEs como Netbeans o Eclipse que tienen terminal integrado y con ellos no funciona `System.console().readLine()` por lo que hay que evitarlo. Viene explicado en el apartado 3 del capítulo 3 del libro **La clase Scanner**.

El problema que tienes se soluciona simplemente usando la clase `Scanner`. Te pongo el código completo:

```java
package cajafuerte;

import java.util.Scanner;

public class CajaFuerte {

  public static void main(String[] args) {
    int intentos = 4;
    int numeroIntroducido;
    boolean acertado = false;

    Scanner s = new Scanner(System.in);
    
    do {
      System.out.print("Introduzca la clave de la caja fuerte: ");
      numeroIntroducido = Integer.parseInt(s.nextLine());

      if (numeroIntroducido == 8888) {
        acertado = true;
      } else {
        System.out.println("Clave incorrecta");
      }

      intentos--;

    } while ((intentos > 0) && (!acertado));

    if (acertado) {
      System.out.println("Ha abierto la caja fuerte.");
    } else {
      System.out.println("Lo siento, ha agotado las 4 oportunidades.");
    }
  }

}
```

Es un error frecuente que me comentan muchos alumnos. Por eso estoy dejando de utilizar `System.console().readLine()` en los ejemplos y ejercicios nuevos que voy añadiendo al libro y usando la clase Scanner como te muestro en este código.

Espero que te sirva y gracias por abrir el hilo, seguro a muchos otros estudiantes les servirá el aporte.

**Comment by shaul403** [comment]
muchas gracias y agradezco su tiempo

**Comment by LuisJoseSanchez** [comment]
Cierro la incidencia.
